//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int ContactID { get; private set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string Notes { get; set; }
        public System.DateTime SubmitTime { get; set; }
    }
}
